### ISSUE TITLE
1.18.2 Shutdown [BUG]

### ISSUE THREAD

**Issue by JaHollTV** [SBDPlugins/V10Lift#60]
**Describe the bug**
Error in console by stop your Server with Paper 1.18.2

**To Reproduce**
Just start and stop your Server with v10lift in 1.18.2

**Expected behavior**
No error

**Screenshots**
"[13:18:25 ERROR]: Error occurred while disabling V10Lift v0.7.3 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[paper-1.18.2.jar:git-Paper-283]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:251) ~[paper-1.18.2.jar:git-Paper-283]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:247) ~[paper-1.18.2.jar:git-Paper-283]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:192) ~[paper-1.18.2.jar:git-Paper-283]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:161) ~[paper-1.18.2.jar:git-Paper-283]
        at nl.SBDeveloper.V10Lift.managers.DBManager.save(DBManager.java:82) ~[V10Lift v0.7.3.jar:?]
        at nl.SBDeveloper.V10Lift.V10LiftPlugin.onDisable(V10LiftPlugin.java:131) ~[V10Lift v0.7.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:515) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.disablePlugins(CraftServer.java:493) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:971) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:803) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]"

**Spigot version (use /version):**
This server is running Paper version git-Paper-283 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: f8e8d6c)

**Plugin version (use /v10lift info), NOT LATEST!!!**
0.7.3

**Additional context**
--> can you build v10lift against paper 1.18.2 and publish it as an update to spigot :) ?

**Comment by stijnb1234** [comment]
Can't help you with this error. I need the error at boot, not at shutdown.

**Comment by JaHollTV** [comment]
there are no errors on boot

`[V10Lift] Enabling V10Lift v0.7.3
[10:51:14 INFO]: [nl.SBDeveloper.V10Lift.utils.hikari.HikariDataSource] V10Lift - Starting...
[10:51:14 INFO]: [nl.SBDeveloper.V10Lift.utils.hikari.HikariDataSource] V10Lift - Start completed.
[10:51:14 INFO]: [V10Lift] Loading lift FrankRedMuseum_1 from data...
[10:51:14 INFO]: [V10Lift] Loading lift FrankRedMuseum_2 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Crim from data...
[10:51:14 INFO]: [V10Lift] Loading lift Brauerei from data...
[10:51:14 INFO]: [V10Lift] Loading lift Matti_Aufzug from data...
[10:51:14 INFO]: [V10Lift] Loading lift FrankRedMuseum_3 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Heizmann_Garage from data...
[10:51:14 INFO]: [V10Lift] Loading lift Matti_Haus from data...
[10:51:14 INFO]: [V10Lift] Loading lift FrankRedMuseum_4 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Feuerwehr2 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Sarah_Blackblood from data...
[10:51:14 INFO]: [V10Lift] Loading lift Iwanow_Turm from data...
[10:51:14 INFO]: [V10Lift] Loading lift Feuerwehr1 from data...
[10:51:14 INFO]: [V10Lift] Loading lift KBG_Aufzug from data...
[10:51:14 INFO]: [V10Lift] Loading lift KBG_Lager_Aufzug from data...
[10:51:14 INFO]: [V10Lift] Loading lift Mine from data...
[10:51:14 INFO]: [V10Lift] Loading lift FFW_Aufzug from data...
[10:51:14 INFO]: [V10Lift] Loading lift Fahrstuhl-Morris-Keller from data...
[10:51:14 INFO]: [V10Lift] Loading lift Morris-Bunker-Fahrstuhl from data...
[10:51:14 INFO]: [V10Lift] Loading lift Syndikat_Tiefgarage_1 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Golden_Eye_Security_Service_keller from data...
[10:51:14 INFO]: [V10Lift] Loading lift Heizmann_Autolift from data...
[10:51:14 INFO]: [V10Lift] Loading lift LCN_Aufzug3 from data...
[10:51:14 INFO]: [V10Lift] Loading lift LCN_Aufzug1 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Müller_Anwesen from data...
[10:51:14 INFO]: [V10Lift] Loading lift Baumsson_Zweck_80 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Braukeller_Morris from data...
[10:51:14 INFO]: [V10Lift] Loading lift Triaden_Tower from data...
[10:51:14 INFO]: [V10Lift] Loading lift Wunder_Tiefgarage_1 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Wunder_Tiefgarage_2 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Silian_Anwesen from data...
[10:51:14 INFO]: [V10Lift] Loading lift ksl_hebebühne_1 from data...
[10:51:14 INFO]: [V10Lift] Loading lift ksl_hebebühne_2 from data...
[10:51:14 INFO]: [V10Lift] Loading lift MS_Fahrstuhl from data...
[10:51:14 INFO]: [V10Lift] Loading lift richter_autolift from data...
[10:51:14 INFO]: [V10Lift] Loading lift LCN_Aufzug2 from data...
[10:51:14 INFO]: [V10Lift] Loading lift PD_Büro from data...
[10:51:14 INFO]: [V10Lift] Loading lift Gefängnis_01 from data...
[10:51:14 INFO]: [V10Lift] Loading lift tg_patrick_01 from data...
[10:51:14 INFO]: [V10Lift] Loading lift df_tg_01 from data...
[10:51:14 INFO]: [V10Lift] Loading lift df_tg_02 from data...
[10:51:14 INFO]: [V10Lift] Loading lift kmh_01 from data...
[10:51:14 INFO]: [V10Lift] Loading lift bt_aufzug_op from data...
[10:51:14 INFO]: [V10Lift] Loading lift Stentenbach_Mosk_Lift from data...
[10:51:14 INFO]: [V10Lift] Loading lift KMH_Hebebühne_2 from data...
[10:51:14 INFO]: [V10Lift] Loading lift KMH_Hebebühne_1 from data...
[10:51:14 INFO]: [V10Lift] Loading lift KMH_Hebebühne_3 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Lebensfroh from data...
[10:51:14 INFO]: [V10Lift] Loading lift the_way_down from data...
[10:51:14 INFO]: [V10Lift] Loading lift SchulteKeller02 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Dark_Tower from data...
[10:51:14 INFO]: [V10Lift] Loading lift Stentenbach_Mosk_Lift2 from data...
[10:51:14 INFO]: [V10Lift] Loading lift SchulteKeller01 from data...
[10:51:14 INFO]: [V10Lift] Loading lift SchulteGarage01 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Bühne_Lehmberg from data...
[10:51:14 INFO]: [V10Lift] Loading lift Rumpe-Tiefgarage from data...
[10:51:14 INFO]: [V10Lift] Loading lift Neumann_Bunker from data...
[10:51:14 INFO]: [V10Lift] Loading lift Veluxo from data...
[10:51:14 INFO]: [V10Lift] Loading lift JM_Aufzug from data...
[10:51:14 INFO]: [V10Lift] Loading lift JM_Keller from data...
[10:51:14 INFO]: [V10Lift] Loading lift KSMC_1 from data...
[10:51:14 INFO]: [V10Lift] Loading lift KSMC_2 from data...
[10:51:14 INFO]: [V10Lift] Loading lift PF_Aufzug from data...
[10:51:14 INFO]: [V10Lift] Loading lift JM_Garage from data...
[10:51:14 INFO]: [V10Lift] Loading lift Evolution-T1 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Evolution-T2 from data...
[10:51:14 INFO]: [V10Lift] Loading lift MJ_Wohnung from data...
[10:51:14 INFO]: [V10Lift] Loading lift FD_Autolift from data...
[10:51:14 INFO]: [V10Lift] Loading lift Bergfeld_Dach from data...
[10:51:14 INFO]: [V10Lift] Loading lift Morris_Industries_Hebebühne_2 from data...
[10:51:14 INFO]: [V10Lift] Loading lift Morris_Industries_Hebebühne_1 from data...
[10:51:14 INFO]: [V10Lift] Loading lift AR_Lift from data...
[10:51:14 INFO]: [V10Lift] Loading lift LO_Tower from data...
[10:51:14 INFO]: [V10Lift] Loading lift MJ_Autolift_2 from data...
[10:51:14 INFO]: [V10Lift] Loading lift MJ_Autolift_1 from data...
[10:51:14 INFO]: [V10Lift] Loading lift KT_Tiefgarage from data...
[10:51:14 INFO]: [V10Lift] Loading lift MJ_Lift from data...
[10:51:14 INFO]: [V10Lift] Loading Vault hook for group whitelist support.
[10:51:14 INFO]: [V10Lift] Loading metrics. Can be disabled in the global bStats config.
[10:51:14 INFO]: [V10Lift] Plugin loaded successfully!`

**Comment by stijnb1234** [comment]
Send me your full log file. Folder logs, then the file latest.log.

**Comment by JaHollTV** [comment]
[latest.log](https://github.com/SBDPlugins/V10Lift/files/8569016/latest.log)

I will not help,
cause as i said there are no errors...


IllegalPluginAccessException: Plugin attempted to register task while disabled --> this is a known mistake you can see many solutions on spigot :)

**Comment by JaHollTV** [comment]
[latestWithShutdown.log](https://github.com/SBDPlugins/V10Lift/files/8569029/latestWithShutdown.log)

**Comment by stijnb1234** [comment]
Thanks. A lot of those tried to register while disabled errors are caused by the plugin disabing at startup. This one indeed is not. I will fix it ASAP.

**Comment by JaHollTV** [comment]
I look forward for the update :)
Is there something i can help with?

**Comment by stijnb1234** [comment]
Not yet. Will update this weekend.

**Comment by JaHollTV** [comment]
Oh my god, time is running!
What about fixing it today, my friend?

**Comment by stijnb1234** [comment]
> Oh my god, time is running! What about fixing it today, my friend?

Let's do that. ;)

**Comment by JaHollTV** [comment]
Hey :)
I don't know why, but the Problem is still there in v0.7.4

`[16:55:01 ERROR]: Error occurred while disabling V10Lift v0.7.4 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[paper-1.18.2.jar:git-Paper-283]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:251) ~[paper-1.18.2.jar:git-Paper-283]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:247) ~[paper-1.18.2.jar:git-Paper-283]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:192) ~[paper-1.18.2.jar:git-Paper-283]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:161) ~[paper-1.18.2.jar:git-Paper-283]
        at nl.SBDeveloper.V10Lift.managers.DBManager.saveLift(DBManager.java:130) ~[V10Lift v0.7.4.jar:?]
        at nl.SBDeveloper.V10Lift.managers.DBManager.save(DBManager.java:115) ~[V10Lift v0.7.4.jar:?]
        at nl.SBDeveloper.V10Lift.V10LiftPlugin.onDisable(V10LiftPlugin.java:126) ~[V10Lift v0.7.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:515) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.disablePlugins(CraftServer.java:493) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:971) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:803) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:931) ~[paper-1.18.2.jar:git-Paper-283]
        at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:92) ~[paper-1.18.2.jar:git-Paper-283]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:61) ~[paper-1.18.2.jar:git-Paper-283]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) ~[paper-1.18.2.jar:git-Paper-283]
        at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1544) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-283]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-283]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by stijnb1234** [comment]
Fixed in v0.7.4.1, now tested it myself. ;)
